"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildLogger = exports.httpClient = exports.httpAxiosClient = exports.generateUUID = exports.getAge = void 0;
const get_age_plugin_1 = require("./get-age.plugin");
Object.defineProperty(exports, "getAge", { enumerable: true, get: function () { return get_age_plugin_1.getAge; } });
const uuid_plugin_1 = require("./uuid.plugin");
Object.defineProperty(exports, "generateUUID", { enumerable: true, get: function () { return uuid_plugin_1.generateUUID; } });
const http_client_plugin_1 = require("./http-client.plugin");
Object.defineProperty(exports, "httpClient", { enumerable: true, get: function () { return http_client_plugin_1.httpClient; } });
const axios_plugin_1 = require("./axios.plugin");
Object.defineProperty(exports, "httpAxiosClient", { enumerable: true, get: function () { return axios_plugin_1.httpAxiosClient; } });
const logger_plugin_1 = require("./logger.plugin");
Object.defineProperty(exports, "buildLogger", { enumerable: true, get: function () { return logger_plugin_1.buildLogger; } });
